- README.rst
- http_prompt/completer.py
- http_prompt/execution.py
- http_prompt/lexer.py
- tests/test_execution.py
Test added and passed.
```
→ python -m pytest
========================================================================== test session starts ==========================================================================
platform darwin -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /Users/karl/code/http-prompt, inifile: tox.ini
plugins: cov-2.2.1
collected 77 items 
tests/test_context.py .......
tests/test_execution.py ..................................................
tests/test_lexer.py ....................
----------------------------------------------------------- coverage: platform darwin, python 2.7.10-final-0 ------------------------------------------------------------
Name                       Stmts   Miss  Cover   Missing …
```
> Adds the HEAD method

- http_prompt/context.py
- http_prompt/execution.py
- tests/test_context.py
- tests/test_execution.py
When passing arguments to `httpie.core.main`, no need to add quotes. But when previewing httpie command (using `httpie get ...` command), we need to quote the arguments.
> Fix #5: Remove quotes from HTTPie arguments

- http_prompt/context.py
- http_prompt/execution.py
- tests/test_context.py
- tests/test_execution.py
This PR respects user's trailing slash:
```
$ http-prompt http://localhost/
http://localhost/> cd api/v1
http://localhost/api/v1> cd things/
http://localhost/api/v1/things/> cd ..
http://localhost/api/v1> cd ../
http://localhost/api/>
```
> Fix #3: Don't strip trailing slash from URL

- http_prompt/cli.py
- http_prompt/completer.py
- http_prompt/options.py
fix #15. 
1. Hitting enter with a only whitespace entered is treated as a NOP command. No syntax error is printed.
2. Added a 'help' command that lists current commands, option flags, actions and headers.
> Added help command and NOP command

- http_prompt/cli.py
- tests/test_cli.py
The motivation of this feature is to be able to pass environment
variables. Although, the drawback is that requires the URL argument to
be passed first, otherwise the first argument will be taken as URL.
Example:
$ export MYAUTH=a1b2c3d4
$ http-prompt http://httpbin.org/get --auth $MYAUTH:
Version: 0.2.1dev
http://httpbin.org/get> httpie
http --auth auth: http://httpbin.org/get
> Handle extra arguments as initial http options.

- http_prompt/execution.py
AttributeError: '_io.BytesIO' object has no attribute 'encoding'. See issue: https://github.com/eliangcs/http-prompt/issues/11
> Fix exception in Windows

- http_prompt/cli.py
- http_prompt/context.py
- http_prompt/xdg.py
- tests/base.py
- tests/test_cli.py
- tests/test_context.py
- tests/test_interaction.py
- tests/test_xdg.py
This PR implements a new feature called **persistent context**. Every time a user types a command and hits enter, http-prompt saves the current context (headers, options, and parameters) to the disk. When the user restarts http-prompt and revisit the same host, the context is loaded back from the disk, so the user can keep working on the same context again without re-entering all those parameters.
Related issues: #10 and #26
> Persistent context

- http_prompt/cli.py
- http_prompt/config.py
- http_prompt/contextio.py
- http_prompt/default_config.py
- http_prompt/defaultconfig.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_contextio.py
This PR allows a user to configure user preferences using a config file. The config file is a Python file named `config.py` located in the config directory. Besides the config directory, there is a data directory used to store session history. The following table list their locations:
| | Unix-like (Linux and OS X) | Windows |
|---|---|---|
|Config directory|`$XDG_CONFIG_HOME/http-prompt`|`%LOCALAPPDATA%/http-prompt`|
|Data directory|`$XDG_DATA_HOME/http-prompt`|`%LOCALAPPDATA%/http-prompt`|
If environment variables are undefined, the locations default to the following values:
| | Unix-like (Linux and OS X) | Windows |
|---|---|---|
|Config directory|`~/.config/http-prompt`|`~/AppData/Local/http-prompt`|
|Data directory|`~/.local/share/http-prompt`|`~/AppData/Local/http-prompt`|
> User config

- http_prompt/cli.py
- http_prompt/context.py
- http_prompt/contextio.py
- http_prompt/execution.py
- tests/test_cli.py
execution.py deals with all execution logic. But cli.py, an outsider module, may be interested in some events. For instance, when a user changes their base URL using `cd`, we should reload the context from the filesystem. This commit implements "execution event listener" to do such a thing.
> Refactor context loading using execution event listener

- http_prompt/cli.py
This will prevent the app from exiting when Control-C is pressed,
instead creating a new prompt.
This is a quick and easy solution for #52. Perhaps a more complex handler for aborts could be made in the future.
> Add RETRY abort handler to the prompt

- http_prompt/execution.py
- tests/test_execution.py
Fix the following scenario:
```
> 'name==John\'s Doe' "name=John\'s Doe"
```
> Fix bug: Quoted strings may contain escaped chars

- http_prompt/execution.py
- tests/test_execution.py
a quick patch that fix following bug:
```
http://localhost> --session-read-only test
Syntax error near "--session-"
http://localhost> --auth-type test
Syntax error near "--auth-typ"
```
after applying the patch:
```
http://localhost> --session-read-only test
http://localhost> --auth-type test
http://localhost> httpie
http --auth-type test --session-read-only test http://localhost --session-read-only=test
```
> Fix bug: Let parser match longer argument first

- http_prompt/execution.py
- http_prompt/lexer.py
- tests/test_execution.py
- tests/test_lexer.py
As title says... lexer rules for shell commands has been fully implemented... I've added some more tests for this as well...
I've a question, though. 
Now, it's possible to define a shell command in full single/double-quoted request mutation. For example, you can do this:
```bash
httpie post "`echo name`=value"
```
Is that the expected behavior, @eliangcs ?
If so, I'll add tests for this...
ps: I'm asking because I couldn't think of a reason why the full single/double-quoted request mutation feature  was implemented in first place...
> shell commands - lexer rules, pipe to shell cmd redirection, tests

- http_prompt/context/transform.py
- tests/context/test_transform.py
When you did:
```bash
localhost> bar:=' "baz" '
```
the command that was saved into `context.hp` was equal:
> bar:="baz"
but expected (wrapped in single quotes):
> bar:='"baz"'
This causes `JSONDecodeError` when trying to load exported context.
Fixes #101 PR
> bugfix for #101 PR raw json data export

- http_prompt/execution.py
- tests/test_execution.py
Example:
```bash
http://localhost:8000/path/to/something> cd
http://localhost:8000>
```
> when `cd` cmd is called without url, reset base url to protocol + hostname

- http_prompt/cli.py
I checked the `.travis.yml` file and it says the earliest Python version being checked is `2.6`. I double-checked the docs and it looks like `str.startswith` has accepted tuples since `2.5`.
> [_Changed in version 2.5:_ Accept tuples as `prefix`.](https://docs.python.org/2.6/library/stdtypes.html?highlight=startswith#str.startswith)
```python
>>> url = 's://'
>>> url.startswith('s://') or url.startswith('://')
True
>>> url.startswith(('s://', '://'))
True
>>> url = '://'
>>> url.startswith('s://') or url.startswith('://')
True
>>> url.startswith(('s://', '://'))
True
>>> url = 'www'
>>> not url.startswith('http://') and not url.startswith('https://')
True
>>> not url.startswith(('http://', 'https://'))
True
```
> Use tuples inside of `str.startswith` (for multiple checks)

- http_prompt/completer.py
It looks like `six.u` only takes one argument but it was being called with two. 
```python
text = six.u(text, 'utf-8')
```
[six.u(text)](https://pythonhosted.org/six/#six.u)
```python
>>> import six
>>> text = 'test_str'
>>> six.u(text)
'test_str'
>>> six.u(text, 'utf-8')
Traceback (most recent call last):
File "<input>", line 1, in <module>
TypeError: u() takes 1 positional argument but 2 were given
```
> Remove extra argument from `six.u` function call

- .gitignore
There is one test called`test_get` from `TestHttpActionRedirection` suite that generates a file. 
This file should be included into .gitignore, since it's a test dump
> Ignoring data.json file which is generated from tests

- .travis.yml
- setup.py
[Parsimonious](https://github.com/erikrose/parsimonious) doesn't support Python 2.6 since 0.8.0. Let's drop it as well.
> Drop Python 2.6 compatibility

- http_prompt/cli.py
- tests/test_cli.py
#132 broke the ability to pass a URL to the `--spec` option. This PR adds a test and fixes the regression.
> Fix bug: Allow passing a URL to --spec

- .travis.yml
- LICENSE
- appveyor.yml
- requirements.txt
prompt_tookit 2.0.0 is going to compatible with 1.x.x, so let's pin its version until we're ready for 2.0.0.
> Upgrade and pin prompt_toolkit

- http_prompt/cli.py
- http_prompt/context/__init__.py
Related to #113, adds support for OpenAPI `host` and `basePath` keys.
> Use host and basePath from OpenAPI spec

- http_prompt/cli.py
- requirements.txt
Swagger specs can be defined in JSON and YAML format.
This PR adds YAML support by falling back to yaml-parsing if JSON-parser throws an error. `PyYaml` is required as additional requirement.
> support swagger spec in yaml format

- http_prompt/context/__init__.py
Swagger allows to reuse common parameters by referencing items of the top-level `parameters` section. The parameter section in `paths` then looks like
```
parameters:
- $ref: "#/parameters/max"
- $ref: "#/parameters/offset"
```
An error is thrown at the moment in that case, because a `name` property is expected and references are not resolved.
This PR resolves references from the top-level parameters object if `$ref` is found.
> support parameter references in swagger spec

- http_prompt/context/__init__.py
- tests/context/test_context.py
Current code expect Path object to contain only method/Operation
declaration. Path object may contain $ref, summary, description, servers
and parameters entries.
If available, this entries are default values to apply children
Operation.
This fix drops unused entries ($ref, summary, description, servers) and
merge parameters:
* unicity based on name/in unicity
* Operation value takes precedence
This fix allows to parse spec file attached with #172
> issue #172: spec/buggy Path/Operation handling

- http_prompt/context/transform.py
- http_prompt/utils.py
Use standard `shelx.quote` to make `httpie` output ready for paste into command line as existing implementation produces incorrectly quoted results in cases like `--auth=username:m8J^a$P9#LdEc`.
> Use standard shlex.quote

- docs/user-guide.rst
I prefer using Homebrew over pip to install CLI tools like this.
So added http-prompt to Homebrew: homebrew/homebrew-core#93458
Just wanted you guys to know that it's now available there.
I also updated the documentation to reflect that.
> Add http-prompt to Homebrew package manager
